import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    descpage: {
        position: 'absolute',
        top: 50,
        right: 30,
        backgroundColor: 'white',
        width: 80,
        height: 35,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
    },
    produtos: {
        width: '90%',
        height: '80%',
        top: 40,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
    },
    scrollview: {
        width: '100%',
    },
    viewtextoproduto: {
        width: '60%',
        alignItems: 'center',
    },
    linha: {
        width: '100%',
        height: 2,
        backgroundColor: 'lightgray',
        margin: 10,
    },
    card: {
        flexDirection: 'row',
        width: '100%',
        height: 170,
        borderWidth: 0,
        padding: 5,
        borderRadius: 15,
        borderColor: '#26a1f4',
    },
    titleproduto: {
        fontSize: 15,
        margin: 5,
        fontWeight: 'bold',
    },
    descproduto: {
        fontSize: 10,
        marginLeft: 10,
    },
    precoproduto: {
        fontSize: 20,
        margin: 3,
        fontWeight: 'bold',
    },
    idades2: {
        width: '50%',
        height: '50%',
        backgroundColor: 'white',
        bottom: 95,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 40,
        right: 10,
        position: 'absolute',
    },
    imgmlk: {
        borderRadius: 10,
        width: '100%',
        height: '100%',
    },
    viewimgmlk: {
        position: 'absolute',
        top: 113,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: '#26a1f4',
        width: '106%',
        height: 160,
    },
    viewimgmidade: {
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
        borderWidth: 4,
        borderColor: '#7CE88C',
        width: 140,
        height: 140,
    },
    imgidade: {
        borderRadius: 10,
        width: 120,
        height: 120,
    },
    textmain: {
        fontSize: 15,
        fontWeight: 'bold',
    },
    viewtextmain: {
        position: 'absolute',
        top: 120,
    },
    textdesc: {
        fontSize: 13,
    },
    textdesc2: {
        color: '#26a1f4',
    },
    viewtextdesc: {
        width: '80%',
        position: 'absolute',
        bottom: 145,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 5,
    },
    viewbutton: {
        borderWidth: 3,
        borderColor: 'lightgray',
        borderRadius: 20,
        position: 'absolute',
        bottom: 170,
        width: '60%',
        height: 27,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#26a1f4',
    },
    viewbutton2: {
        borderWidth: 3,
        borderColor: 'lightgray',
        borderRadius: 20,
        position: 'absolute',
        bottom: 18,
        width: '70%',
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#26a1f4',
    },
    touchbutton: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    textbutton: {
        fontSize: 16,
        color: 'white',
    },
    form: {
        width: '60%',
        height: '30%',
        top: 80,
        gap: 5,
    },
    input: {
        backgroundColor: 'white',
        borderRadius: 6,
        height: '19%',
        width: '100%',
        borderWidth: 2,
        borderColor: '#26a1f4',
        padding: 10,
    },
    form: {
        width: '60%',
        height: '30%',
        justifyContent: 'center',
        alignItems: 'center',
        top: 50,
        gap: 2,
    },
})